---
# Run all tests
stages:
  - deployment test

before_script:
  - ansible --version
  - molecule --version

variables:
  GET_SOURCES_ATTEMPTS: "5"

AWS endeca-toolsandframeworks 11.3.0:
  variables:
    EPC_REGION: AWS-EUCENTRAL
  stage: deployment test
  script:
    - molecule test -s cloud-aws-11.3.0
  tags:
    - delegated

EPC endeca-toolsandframeworks 11.3.0:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-11.3.0
  tags:
    - delegated

Docker endeca-toolsandframeworks 11.x:
  stage: deployment test
  script:
    - molecule test -s docker-11.3.0-centos-7
    - molecule test -s docker-11.3.0-centos-6
    - molecule test -s docker-11.2.0-centos-7
    - molecule test -s docker-11.2.0-centos-6
    - molecule test -s docker-11.1.0
  tags:
    - docker

Docker endeca-toolsandframeworks 3.1.2:
  stage: deployment test
  script:
    - molecule test -s docker-3.1.2
  tags:
    - docker

Docker endeca-toolsandframeworks 3.1.0:
  stage: deployment test
  script:
    - molecule test -s docker-3.1.0
  tags:
    - docker
