---
- name: "Update workbench password for oracle.endeca.commerce component type"
  block:

    # installing pexpect through easy_install to avoid installing pip
    # temporarily workaround with rescue section until bug will be resolved
    # https://github.com/ansible/ansible/issues/23534
    - name: "Install pexpect section"
      block:

        - name: "Install pexpect using ansible easy_install module"
          easy_install:
            name: "pexpect"
            state: "present"
      rescue:
        - name: "Install pexpect using python easy_install"
          command: "easy_install pexpect"

      become: True

    - name: "Updating password in ifcr for versions higher 11.1"
      block:

        - name: "Check ToolsAndFrameworks host availability"
          uri:
            url: "http://{{ ansible_hostname }}:{{ workbench_port }}/ifcr/login"
            method: "GET"
            return_content: True
          register: tf_host
          until: tf_host.status == 200
          retries: "20"
          delay: "10"

        - name: "Change default workbench admin password"
          uri:
            url: "http://{{ ansible_hostname }}:{{ workbench_port }}\
            /ifcr/system/userManager/user/admin.changePassword.json"
            user: "{{ workbench_user }}"
            password: "{{ workbench_password_default }}"
            method: "POST"
            body: "oldPwd={{ workbench_password_default }}&newPwd={{ workbench_password }}\
            &newPwdConfirm={{ workbench_password }}"
            return_content: True
            headers:
              Content-Type: "application/x-www-form-urlencoded"
            status_code: "200"
            timeout: "300"

      when: tf_version is version ('11.1.0', '>')

    - name: "Set responses for manage_credentials.sh for versions lower 11.3"
      set_fact:
        credentials_responses:
          'Enter password for user admin :': "{{ workbench_password }}"
          'Re\-enter password to confirm :': "{{ workbench_password }}"
          'Do you want to replace it \[yes/no\] \?': "yes"
      when: tf_version is version ('11.2.0', '<=')

    - name: "Set responses for manage_credentials.sh for versions higher 11.2"
      set_fact:
        credentials_responses:
          'Enter new password for user admin :': "{{ workbench_password }}"
          'Re-\enter new password to confirm :': "{{ workbench_password }}"
          'Do you want to replace it \[yes/no\] \?': "yes"
      when: tf_version is version ('11.2.0', '>')

    - name: "Run manage_credentials.sh"
      expect:
        chdir: "{{ tf_path }}/credential_store/bin"
        command: "./manage_credentials.sh add --user admin --config \
        {{ tf_path }}/server/workspace/credential_store/jps-config.xml --key ifcr"
        responses: "{{ credentials_responses }}"
      environment:
        ENDECA_ROOT: "{{ base_root }}/endeca/PlatformServices/{{ ps_version }}"
      become_user: "{{ endeca_user }}"
      become: True

    - name: "Restart ToolsAndFrameworks"
      service:
        name: "{{ tf_service }}"
        state: "restarted"
      become: True

  when: commerce_type.matched | bool
