---
- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.endeca_mdex
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-commerce-suite/commerce/endeca11.1/V46002-01.zip"
    - role: lean_delivery.endeca_platformservices
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-commerce-suite/commerce/endeca11.1/V45999-01.zip"
    - role: ansible-role-endeca-toolsandframeworks
      tf_version: "11.1.0"
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-commerce-suite/commerce/endeca11.1/V46389-01.zip"
      workbench_password: "Admin123"
  vars:
    mdex_version: "6.5.1"
    ps_version: "11.1.0"
